version: "3.8"

services:
  taxi-server-tdio:
    build:
      context: ./server
    command: python manage.py runserver 0.0.0.0:8000
    container_name: taxi-server-tdio
    depends_on:
      - taxi-redis-tdio
      - taxi-database-tdio
    environment:
      - PGDATABASE=taxi
      - PGUSER=taxi
      - PGPASSWORD=taxi
      - PGHOST=taxi-database-tdio
      - REDIS_URL=redis://taxi-redis-tdio:6379/0
    ports:
      - 8003:8000
    volumes:
      - ./server:/usr/src/app

  taxi-redis-tdio:
    container_name: taxi-redis-tdio
    image: redis:6-alpine

  taxi-database-tdio:
    container_name: taxi-database-tdio
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=taxi
      - POSTGRES_PASSWORD=taxi
    expose:
      - 5432
    volumes:
      - taxi-database-tdio:/var/lib/postgresql/data

  taxi-client-tdio:
    build:
      context: ./client
    command: npm start
    container_name: taxi-client-tdio
    depends_on:
      - taxi-server-tdio
    ports:
      - 3001:3000
    stdin_open: true
    volumes:
      - ./client:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL=http://localhost:8003
      - REACT_APP_GOOGLE_MAPS_KEY=AIzaSyDKjUbUwPCSCeLJ6rgDiXgiZapObZ4Hebg

volumes:
  taxi-database-tdio:
